### ISSUE TITLE
Inconsistency in Moon file naming

### ISSUE THREAD

**Issue by dgasmith** [bennybp/planets#1]
In the primary project folder some Moon names are connected to planets and others are not linked. For example you have the files "Earth" and "Luna" and then Jupiter's moons is named "Jupyter_moons".

There are many more issues than this; however, I would like to focus on the organization issue here. I would like to merge the moon data into the planets file under a Markdown H2 level.

PS: "Luna" is the only name in Spanish/Latin in the directory.

**Comment by bennybp** [comment]
Good catch. What do you propose as a good solution?

**Comment by dgasmith** [comment]
Hi Ben,
Was the second paragraph not clear enough? I just would like to merge the files together under the planets name.

**Comment by bennybp** [comment]
Ok. Can you make a pull request?

**Comment by dgasmith** [comment]
Yea, I can do that.
