### ISSUE TITLE
Incorrect info in Sun

### ISSUE THREAD

**Issue by mtesseracted** [bennybp/planets#3]
Our sun in not large enough to fuse anything heavier than Carbon and is not large enough to go supernova.

**Comment by mtesseracted** [comment]
https://en.wikipedia.org/wiki/Carbon-burning_process

**Comment by dgasmith** [comment]
CNO cycle in Sol: http://iopscience.iop.org/article/10.1088/1742-6596/271/1/012031/meta

**Comment by mtesseracted** [comment]
So it will make up to Oxygen: http://www.astro.cornell.edu/academics/courses/astro201/evol_sun.htm
The file says 'heavy elements', which in astrophysical terms usually means elements heavier than iron.

**Comment by mtesseracted** [comment]
Typical astrophysical article describing heavy elements: http://spie.org/newsroom/2923-the-origin-of-the-heavy-elements?SSO=1

**Comment by mtesseracted** [comment]
Fixed in pull #22
