### ISSUE TITLE
Clarification needed in age of Jupiter storm

### ISSUE THREAD

**Issue by eirrgang** [bennybp/planets#4]
https://github.com/bennybp/planets/blob/aad4acde043752b69b38da940b0041107de3ed8e/Jupiter#L4
The annotation implies the storm has existed for thousands of years, but may refer instead to the storm's projected lifetime, since it has only been confirmed to be hundreds of years old.
https://en.wikipedia.org/wiki/Great_Red_Spot

I propose to change "thousands" to "hundreds" pending further clarification.

**Comment by bennybp** [comment]
True. I don't know why they did that. Can you make that change and clarify that it is only the confirmed age?
