### ISSUE TITLE
README.md is incomplete and non-descriptve

### ISSUE THREAD

**Issue by chemphys** [bennybp/planets#9]
Hello, I was looking at the repo and I just realized that the README is not complete. I can complete it for you adding what does this repository contains.

I will create a pull request in a bit.

**Comment by bennybp** [comment]
I've been meaning to get around to that...

But if you can help that would be great!

**Comment by dgasmith** [comment]
Can you coordinate with #7, who is already working on this. Perhaps take different parts.

**Comment by chemphys** [comment]
I am closing this issue since there is already #7 ongoing.
